### PR TITLE
Fixes #19 - 0 is not undefined anymore in labels

### LINKED ISSUE #19: labelInterpolationFnc 0 gets passed as undefined
Hello! If not set, `labelInterpolationFnc` will use Chartist.noop. However, my chart shows `undefined` instead of `0`.

I had to apply this function to fix this:
```js
{
    labelInterpolationFnc: v=>v?v:0
}
```

### PR DESCRIPTION
**Pull request by MartinMuzatko**

### CODE REVIEW

**Comment by stomachfat** [comment]
Hey @MartinMuzatko ! Ty for the submission, could help explain something to me ... 

I must be having a total oversight ... 

`Chartist.noop` just takes the first arg and returns it 
see: https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js#L56
... so doesn't it do the exact thing as your function when we pass it `0`

**Comment by catsofmath** [comment]
Heyy @MartinMuzatko  thanks for putting in a fix, I don't agree with it! 

The problem isn't the default `labelInterpolationFnc` being set to `Chartist.noop`
In fact `Chartist.noop` is returning `0` just as your function `function(value) {return value ? value: 0}` would return `0` if it were also fed `0`. 

The problem is `value` in this library is calculated wrong... where 
`value` comes from 

```
      var value = data.value.x !== undefined && data.value.y ?
        (data.value.x + ', ' + data.value.y) :
        data.value.y || data.value.x;
```

https://github.com/gionkunz/chartist-plugin-pointlabels/blob/master/src/scripts/chartist-plugin-pointlabels.js#L56

**Comment by catsofmath** [comment]
Let me put a fix in : ) and I'll tag you and you can tell me what you think !

**Comment by catsofmath** [comment]
Please see https://github.com/gionkunz/chartist-plugin-pointlabels/pull/26

**Comment by MartinMuzatko** [comment]
Thanks @stomachfat ! I'll look into. I know I were fixing a symptom because I didn't look too deep into the code, I'd rather have your fix :)

**Pull request closed without merging**
